### ISSUE TITLE
Theme compatibility: Atahualpa

### ISSUE THREAD

**Issue by aharonium** [JoryHogeveen/off-canvas-sidebars#110]
Alas, after installing the Off-canvas Sidebars & Menus plugin (0.5.7.1), I was unable to get it working on the widely used and venerable Wordpress theme, Atahualpa (3.7.26). 

I followed the simple theme setup to add the relevant code to the header.php and footer.php after and before the `<body>`, `</body>` tags. After adding the hooks, the validation error that appeared was "Off-Canvas Sidebars are not direct children of the HTML body tag." I did confirm that the osd code was in the page source immediately after and before the `<body>` and `</body>` tags, respectively, but it still didn't work. So it goes.

I did notice that while `<?php wp_footer(); ?>` was already present in footer.php, `wp_body_open()` did not appear in the header. I added `<?php do_action('website_before'); ?>` immediately after the `<body>` tag.

If anyone has any ideas, I'm happy to try them out, and thank you for your work on this plugin.

(WP 5.8.2, PHP 7.4.25.)

**Comment by JoryHogeveen** [comment]
Hi @aharonium 

Atahualpa is a very (very very) old thema that isn't maintained anymore since 2015: https://wordpress.org/themes/atahualpa/
It even uses non-responsive tables for it's structure.

For that reason I wouldn't recommend using this theme since it will definitely not 100% support the latest versions of WP core and moest plugins.

A theme this old will most likely require some custom changes to make it work. It will most likely render some incorrect HTML which cause the validator to throw errors.
Do you have a link for me to look?

Cheers, Jory

**Comment by JoryHogeveen** [comment]
No problem, you can always try several configuration and dive into the theme more to try and make it compatible.
Custom development from my end to make your theme compatible that is that old is definitely out of scope for support.
Cheers! Jory
