### ISSUE TITLE
Compatibility with Divi Theme

### ISSUE THREAD

**Issue by dimu505** [JoryHogeveen/off-canvas-sidebars#49]
## Expected Behavior
Is this plugin compatible with the divi theme?  carbonsignature.com 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Plugin Version:
  - WordPress Version:
  - Other plugins installed:
  - Theme:
  - Browser:

**Comment by JoryHogeveen** [comment]
@dimu505 
I'm not sure. The link you provided redirects to a login page.
I think it's best to ask the Divi support, they will know if there are existing hooks that are compatible with this plugin.
My experience with such large themes is that there is some customization required in order to get it compatible.

Please let me know if/how you got it working and/or if I can help!

**Comment by JoryHogeveen** [comment]
Hi @dimu505,
Just wondering, did you manage to get Divi to work with this plugin?
Thanks!

**Comment by dimu505** [comment]
Yes I did.  It took some configuration of the plugin

Rick Hodges Jr. | Web Designer
Viridian Geeks – Web Development Firm
• 470 - 440 - 3434
• rhodges@viridiangeeks.com<mailto:rhodges@viridiangeeks.com>
• Viridian Geeks | Atlanta | GA |30360
[viridian-geeks-logo-signature]
                 www.viridiangeeks.com<http://www.viridiangeeks.com/>

**Comment by JoryHogeveen** [comment]
@dimu505 
Sorry for my late reply.
I was curious what you needed to configure/change to make Divi compatible.. Or was it just compatible with this plugin basic configuration?
Thanks!
